### ISSUE TITLE
Unable to locate element: .//div[@class='speed-control ']

### ISSUE THREAD

**Issue by AoElite** [Djaenk/zyBooks-Activity-Completer#15]
Starting chapter 10 section 1...
Traceback (most recent call last):
  File "C:\Users\roxie\Desktop\ZyBookSolver\zyBooks-Activity-Completer-0.2.2\complete.py", line 289, in <module>
    sectionSelection(driver, chapter)
  File "C:\Users\roxie\Desktop\ZyBookSolver\zyBooks-Activity-Completer-0.2.2\complete.py", line 108, in sectionSelection
    completeParticipationActivities(driver)
  File "C:\Users\roxie\Desktop\ZyBookSolver\zyBooks-Activity-Completer-0.2.2\complete.py", line 117, in completeParticipationActivities
    playAnimations(driver)
  File "C:\Users\roxie\Desktop\ZyBookSolver\zyBooks-Activity-Completer-0.2.2\complete.py", line 130, in playAnimations
    double_speed = animation.find_element_by_xpath(".//div[@class='speed-control ']")
  File "C:\Users\roxie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 351, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\roxie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "C:\Users\roxie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\roxie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\roxie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .//div[@class='speed-control ']

**Comment by JartanFTW** [comment]
Send the exception.log file that is generated on error. Can't do much without it.
