### ISSUE TITLE
Cannot seem to get it to work on Mac

### ISSUE THREAD

**Issue by ghost** [Djaenk/zyBooks-Activity-Completer#3]
Please forgive me as I am relatively new to python and GitHub in general so sorry if the answer is obvious. 

I couldn't get it to work as it was so I installed geckodriver for Mac and stored it in /usr/local/bin. I then edited complete.py and did driver = webdriver.Firefox(executable_path = '/usr/local/bin/geckodriver'). Once I did that it seemed to run and open Firefox okay but then after typing my email and hitting enter I got:

Traceback (most recent call last):
  File "complete.py", line 267, in <module>
    login(driver)
  File "complete.py", line 17, in login
    email = input("Please enter your zyBooks email: ")
  File "<string>", line 1
    name@email.com
          ^
SyntaxError: invalid syntax

not sure if there's something I'm doing wrong or if it just isn't meant to run on Mac

Again sorry if the answer is obvious, I am not very familiar with GitHub and python,  just trying to use this to fill in my zybook lol

**Comment by Djaenk** [comment]
I'm actually not sure why this isn't working. There's a chance it simply doesn't work on Mac, but I don't see a reason why, especially since it's able to open the Firefox window.

**Comment by trosnerMSU** [comment]
I have those same issues and I am on windows 10

**Comment by Djaenk** [comment]
The issue could be that the scripts are being run in python 2 instead of 3, which has a different operation associated with input(). But other than that, I still don't have an answer to this bug.
