### ISSUE TITLE
Does not complete all activities and skips some sections

### ISSUE THREAD

**Issue by springisSprong** [Djaenk/zyBooks-Activity-Completer#7]
Login Successful
zyBook Selected

Enter the chapter number you want completed: 4
Chapter Selected

Enter the section number you want completed. Enter "all" if you would like the entire chapter completed: all

Starting chapter 4 section 1...
Completed animation activity
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set

Starting chapter 4 section 2...

Starting chapter 4 section 3...
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set

Starting chapter 4 section 4...
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Completed short answer set
Completed short answer set

Starting chapter 4 section 5...
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set

Starting chapter 4 section 6...

Starting chapter 4 section 7...
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set

Starting chapter 4 section 8...
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set

Starting chapter 4 section 9...
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set

Starting chapter 4 section 10...
Completed multiple choice set
Completed multiple choice set
Completed multiple choice set
Traceback (most recent call last):
  File "complete.py", line 292, in <module>
    sectionSelection(driver, chapter)
  File "complete.py", line 112, in sectionSelection
    driver.find_element_by_xpath("/html/body/div[3]/header/div[1]/div/ul/a[2]/li").click()
  File "C:\Users\choxi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\choxi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\choxi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\choxi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/div[3]/header/div[1]/div/ul/a[2]/li

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "complete.py", line 300, in <module>
    log.write(driver.page_source)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2200' in position 116696: character maps to <undefined>

**Comment by springisSprong** [comment]
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_1.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243196/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_1.txt)
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_2.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243198/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_2.txt)
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_3.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243199/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_3.txt)
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_4.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243200/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_4.txt)
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_5.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243201/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_5.txt)
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_6.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243202/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_6.txt)
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_7.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243203/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_7.txt)
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_8.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243204/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_8.txt)
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_9.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243205/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_9.txt)
[https _learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_10.txt](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5243206/https._learn.zybooks.com_zybook_WISCCOMPSCI240MATH240HastiFall2020_chapter_4_section_10.txt)

**Comment by Djaenk** [comment]
These files are the pre-rendered javascript and not useful for debugging. I need a copy-paste of the html rendered by a browser after each page has loaded.
